default: &default
  adapter: postgresql
  encoding: unicode
  pool:  5

development:
  <<: *default
  database: videoko_development

test:
  <<: *default
  database: videoko_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: videoko_production
  username: postgres
  password: <%= Rails.application.credentials[:password_pg] %>


#default: &default
#  adapter: sqlite3
#  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#  timeout: 15000

#development:
#  <<: *default
#  database: db/development.sqlite3

#test:
#  <<: *default
#  database: db/test.sqlite3

#production:
#  <<: *default
#  database: db/production.sqlite3
